# Generated by Django 3.2.16 on 2023-11-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(max_length=100, unique=True)),
                ('Design_Description', models.CharField(max_length=100)),
                ('Design_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('CreateDate', models.DateField(blank=True, null=True)),
                ('LaunchDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_Name', models.CharField(max_length=100, unique=True)),
                ('Color_Description', models.CharField(max_length=100)),
                ('Color_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('CreateDate', models.DateField(blank=True, null=True)),
                ('LaunchDate', models.DateField(blank=True, null=True)),
                ('Design_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_spec.designs')),
            ],
        ),
    ]
