# Generated by Django 3.2.16 on 2023-11-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bedlinen_fabrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedlinen_name', models.CharField(blank=True, choices=[('TENCEL LYOCELL', 'TENCEL LYOCELL'), ('TENCEL MODAL', 'TENCEL MODAL'), ('BAMBOO', 'BAMBOO'), ('LONG STAPLE COTTON', 'LONG STAPLE COTTON'), ('COTTON', 'COTTON'), ('POLY TENCEL', 'POLY TENCEL'), ('SAME AS SKU', 'SAME AS SKU')], max_length=100, null=True)),
                ('line', models.CharField(blank=True, choices=[('ROTARY REACTIVE PRINT', 'ROTARY REACTIVE PRINT'), ('ROTARY DISPERSE PRINT 圆网分散印花', 'ROTARY DISPERSE PRINT 圆网分散印花'), ('SAME AS SKU', 'SAME AS SKU')], max_length=100, null=True)),
                ('composition', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_list', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('main_pr_type', models.CharField(blank=True, choices=[('Trade', 'Trade'), ('Non Trade', 'Non Trade')], default='Trade', max_length=100, null=True)),
                ('pr_category', models.CharField(blank=True, choices=[('Import', 'Import'), ('Local', 'Local')], default='Import', max_length=100, null=True)),
                ('pr_product', models.CharField(blank=True, choices=[('FG', 'FG'), ('RAWMAT', 'RAWMAT'), ('S-FG', 'S-FG')], max_length=100, null=True)),
                ('plan_otf', models.DateField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('sl_status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], max_length=100, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_collection')),
            ],
        ),
        migrations.CreateModel(
            name='SL_Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_send_date', models.DateField(blank=True, null=True)),
                ('sample_type', models.CharField(blank=True, choices=[('NPI', 'NPI'), ('PP', 'PP'), ('SS', 'SS'), ('Lab Dip', 'Lab Dip')], max_length=100, null=True)),
                ('sample_qty', models.IntegerField(blank=True, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('bedlinen_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.bedlinen_fabrics')),
                ('product_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_sku')),
                ('shopping_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_receive_date', models.DateField(blank=True, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=100)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('product_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_sku')),
                ('shopping_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist')),
            ],
        ),
    ]
