# Generated by Django 3.2.16 on 2023-11-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design_spec', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Collection_Name', models.CharField(max_length=100, unique=True)),
                ('collection_product_category', models.CharField(blank=True, choices=[('Bedlinen', 'Bedlinen'), ('Bath', 'Bath'), ('Towels', 'Towels'), ('Curtains', 'Curtains'), ('Rugs', 'Rugs'), ('Cushions', 'Cushions'), ('RawMat', 'RawMat'), ('H&L', 'H&L'), ('Mix', 'Mix')], max_length=100, null=True)),
                ('Collection_Description', models.CharField(max_length=100)),
                ('CreateDate', models.DateField(blank=True, null=True)),
                ('LaunchDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Country', models.CharField(choices=[('MY', 'MY'), ('SG', 'SG'), ('KN', 'KN'), ('PH', 'PH'), ('VN', 'VN')], max_length=100)),
                ('Company', models.CharField(choices=[('Eastern Decorator Sdn Bhd', 'Eastern Decorator Sdn Bhd'), ('Eadess SG Pte Ltd', 'Eadess SG Pte Ltd'), ('Akemi International (M) Sdn Bhd', 'Akemi International (M) Sdn Bhd')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabric_Type', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M Coor', 'M Coor'), ('M Panel', 'M Panel'), ('Others', 'Others'), ('N/A', 'N/A')], max_length=100)),
                ('Fabric_Composition', models.CharField(max_length=100)),
                ('Yarn_Count_Warp', models.CharField(max_length=100)),
                ('Yarn_Count_Weft', models.CharField(max_length=100)),
                ('Greige_Construction_Warp', models.CharField(max_length=100)),
                ('Greige_Construction_Weft', models.CharField(max_length=100)),
                ('Finished_Construction_Warp', models.CharField(max_length=100)),
                ('Finished_Construction_Weft', models.CharField(max_length=100)),
                ('Finished_Width_CM', models.CharField(max_length=100)),
                ('Usable_Width_CM', models.CharField(max_length=100)),
                ('Fabric_Weight_GSM', models.CharField(max_length=100)),
                ('Weaving_Structure', models.CharField(max_length=100)),
                ('Product_Collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_collection')),
                ('material_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materials')),
            ],
        ),
        migrations.CreateModel(
            name='Product_SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('product_category', models.CharField(blank=True, choices=[('Bedlinen', 'Bedlinen'), ('Bath', 'Bath'), ('Towels', 'Towels'), ('Curtains', 'Curtains'), ('Rugs', 'Rugs'), ('Cushions', 'Cushions'), ('RawMat', 'RawMat'), ('H&L', 'H&L')], max_length=100, null=True)),
                ('pcs_set', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Description', models.CharField(max_length=100)),
                ('Product_CreateDate', models.DateField(blank=True, null=True)),
                ('Product_LaunchDate', models.DateField(blank=True, null=True)),
                ('SKU', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(max_length=100)),
                ('cbm_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('UOM', models.CharField(blank=True, choices=[('Meter', 'M'), ('Set', 'Set'), ('Pcs', 'Pcs'), ('KG', 'KG'), ('Pack', 'Pack')], max_length=100, null=True)),
                ('UOM1', models.CharField(blank=True, choices=[('Meter', 'M'), ('Set', 'Set'), ('Pcs', 'Pcs'), ('KG', 'KG'), ('Pack', 'Pack')], max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Status', models.CharField(choices=[('Active', 'Active'), ('New', 'New'), ('List In', 'List In'), ('Discontinued', 'Discontinued')], max_length=100)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('M1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('M2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('M_Coor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('M_Panel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Collection_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_collection')),
                ('Color_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_spec.colors')),
                ('Design_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_spec.designs')),
                ('Product_Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_country')),
            ],
            options={
                'unique_together': {('Collection_Name', 'Product_Name', 'SKU', 'Design_Name', 'Color_Name')},
            },
        ),
    ]
