# Generated by Django 3.2.16 on 2023-11-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTemplateItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('Test_Property', models.CharField(max_length=100)),
                ('Test_Standard', models.CharField(max_length=100)),
                ('Standard_Quality_Information', models.CharField(max_length=100)),
                ('Test_Requirement', models.CharField(max_length=100)),
                ('Requirement_Lower_Range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Requirement_Upper_Range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Testing_Line', models.CharField(max_length=100)),
                ('Initial_Values', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Line_Result_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=100)),
                ('Comments', models.CharField(max_length=100)),
                ('Test_By', models.CharField(max_length=100)),
                ('Date_Of_Test', models.DateField(blank=True, null=True)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='images/')),
                ('material_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materials')),
            ],
        ),
    ]
