# Generated by Django 3.2.16 on 2023-12-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('quality2', '0002_auto_20231201_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitytemplateitems',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='qualitytemplateitems',
            name='template_name',
        ),
        migrations.AddField(
            model_name='qualitytemplate',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materials'),
        ),
    ]
