# Generated by Django 3.2.16 on 2023-12-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality2', '0003_auto_20231201_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytemplate',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitytemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualitytemplate',
            name='product_category',
            field=models.CharField(choices=[('Bedlinen', 'Bedlinen'), ('Bath', 'Bath'), ('Towels', 'Towels'), ('Curtains', 'Curtains'), ('Rugs', 'Rugs'), ('Cushions', 'Cushions'), ('RawMat', 'RawMat'), ('H&L', 'H&L')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
