# Generated by Django 3.2.16 on 2023-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality2', '0005_auto_20231201_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiqualityschedules',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Scheduled', 'Not Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Scheduled', max_length=100, null=True),
        ),
    ]
