# Generated by Django 3.2.16 on 2023-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality2', '0006_alter_rfiqualityschedules_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitytemplateitems',
            old_name='Initial_Values',
            new_name='Spec_Value',
        ),
        migrations.RemoveField(
            model_name='qualitytemplateitems',
            name='Line_Result_Value',
        ),
        migrations.AddField(
            model_name='qualitytemplateitems',
            name='dim',
            field=models.CharField(blank=True, choices=[('Dimensions', 'Dimensions'), ('Sample', 'Sample'), ('Repetitions', 'Repetitions')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Initial_Values',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Line_Result_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Redo', 'Redo')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Testing_Line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Variance_Percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='Variance_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rfiqualityschedules',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
