# Generated by Django 3.2.16 on 2023-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality2', '0007_auto_20231202_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfiqualityschedules',
            name='Initial_Values',
        ),
        migrations.RemoveField(
            model_name='rfiqualityschedules',
            name='Testing_Line',
        ),
        migrations.AlterField(
            model_name='rfiqualityschedules',
            name='Result',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Pass', 'Pass'), ('Fail', 'Fail'), ('Redo', 'Redo')], max_length=100, null=True),
        ),
    ]
