# Generated by Django 3.2.16 on 2023-12-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality2', '0010_auto_20231203_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytemplateitems',
            name='dim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
