# Generated by Django 3.2.16 on 2023-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, unique=True)),
                ('material_type', models.CharField(choices=[('TENCEL LYOCELL', 'TENCEL LYOCELL'), ('TENCEL MODAL', 'TENCEL MODAL'), ('BAMBOO', 'BAMBOO'), ('LONG STAPLE COTTON', 'LONG STAPLE COTTON'), ('COTTON', 'COTTON'), ('COTTON with ADM', 'COTTON with ADM'), ('COTTON, POLYCOTTON', 'COTTON, POLYCOTTON'), (' POLYESTER (75gsm - 90gsm)', ' POLYESTER (75gsm - 90gsm)'), (' POLYESTER (>100gsm)', ' POLYESTER (>100gsm)'), ('MICRO TENCEL COTTON  ', 'MICRO TENCEL COTTON  '), ('TENCEL BAMBOO CHARCOAL ', 'TENCEL BAMBOO CHARCOAL '), ('SUPIMA COTTON', 'SUPIMA COTTON'), ('POLYESTER (75gsm - 90gsm)', 'POLYESTER (75gsm - 90gsm)'), ('POLYESTER (>100gsm)', 'POLYESTER (>100gsm)'), ('Others', 'Others')], max_length=100)),
            ],
        ),
    ]
