# Generated by Django 3.2.16 on 2023-12-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('Management', 'Management'), ('Finance', 'Finance'), ('Purchasor', 'Purchasor'), ('Requestor', 'Requestor'), ('Shipper', 'Shipper'), ('Quality Manager', 'Quality Manager'), ('Quality User', 'Quality User'), ('Vendor', 'Vendor')], default='Management', max_length=300),
        ),
    ]
