# Generated by Django 3.2.16 on 2023-11-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualitySchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QualitySamples', models.CharField(max_length=100)),
                ('Test_Serial_No', models.CharField(max_length=100)),
                ('Requestor', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Purpose_of_testing', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Product_Category', models.CharField(max_length=100)),
                ('Product_Sub_Category', models.CharField(max_length=100)),
                ('Collection', models.CharField(max_length=100)),
                ('Description_1', models.CharField(max_length=100)),
                ('Description_2', models.CharField(max_length=100)),
                ('SKU', models.CharField(max_length=100)),
                ('Source_entity', models.CharField(max_length=100)),
                ('Vendor_Name', models.CharField(max_length=100)),
                ('Vendor_Code', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('RFI_No_RFQ_No_PO_No', models.CharField(max_length=100)),
                ('Item_No', models.CharField(max_length=100)),
                ('Barcode', models.CharField(max_length=100)),
                ('Delivery_Location_Code', models.CharField(max_length=100)),
                ('Launch_week', models.CharField(max_length=100)),
                ('Launch_month', models.CharField(max_length=100)),
                ('Target_Shipment_Date', models.DateField(blank=True, null=True)),
                ('Date_Parcel_Send', models.DateField(blank=True, null=True)),
                ('Courier_Company_Other', models.CharField(max_length=100)),
                ('Tracking_Number', models.CharField(max_length=100)),
                ('Date_Parcel_Arrive_EA2', models.DateField(blank=True, null=True)),
                ('Sample_Receive_Date_by_Lab', models.DateField(blank=True, null=True)),
                ('Estimated_Result_Date', models.DateField(blank=True, null=True)),
                ('Estimated_Result_Date_Rev_1', models.DateField(blank=True, null=True)),
                ('Reason_to_Reshedule_Rev_1', models.CharField(max_length=100)),
                ('Estimated_Result_Date_Rev_2', models.DateField(blank=True, null=True)),
                ('Reason_to_Reshedule_Rev_2', models.CharField(max_length=100)),
                ('Date_Receive_Complete_Document', models.DateField(blank=True, null=True)),
                ('Date_Start_Test', models.DateField(blank=True, null=True)),
                ('Actual_result_released_date', models.DateField(blank=True, null=True)),
                ('Fabric_Type_M_C_P', models.CharField(max_length=100)),
                ('Special_request', models.CharField(max_length=100)),
                ('Posting_Date', models.DateField(blank=True, null=True)),
                ('Remarks', models.CharField(max_length=100)),
                ('Overall_status', models.CharField(max_length=100)),
                ('QM_Final_Disposition', models.CharField(max_length=100)),
                ('Requestor_Disposition', models.CharField(max_length=100)),
                ('Assign_To', models.CharField(choices=[('Melvin', 'Melvin'), ('Sam', 'Sam'), ('Lai Yen', 'Lai Yen'), ('Qin', 'Qin')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QualityTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=100)),
                ('CreateDate', models.DateField(blank=True, null=True)),
                ('source_entity', models.CharField(choices=[('Import', 'Import'), ('Local', 'Local')], max_length=100)),
                ('category', models.CharField(choices=[('RAWMAT', 'RAWMAT'), ('FG', 'FG'), ('S-FG', 'S-FG')], max_length=100)),
                ('product_category', models.CharField(choices=[('FABRICS', 'FABRICS'), ('PACKAGING ACC', 'PACKAGING ACC'), ('INTERIOR', 'INTERIOR'), ('BEADS', 'BEADS'), ('FIBRE', 'FIBRE'), ('H&L', 'H&L')], max_length=100)),
            ],
            options={
                'unique_together': {('Name', 'Description', 'source_entity', 'category', 'product_category')},
            },
        ),
        migrations.CreateModel(
            name='QualityTemplateItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Property', models.CharField(max_length=100)),
                ('Test_Standard', models.CharField(max_length=100)),
                ('Standard_Quality_Information', models.CharField(max_length=100)),
                ('Test_Requirement', models.CharField(max_length=100)),
                ('Requirement_Lower_Range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Requirement_Upper_Range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Testing_Line', models.CharField(max_length=100)),
                ('Initial_Values', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Line_Result_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=100)),
                ('Comments', models.CharField(max_length=100)),
                ('Test_By', models.CharField(max_length=100)),
                ('Date_Of_Test', models.DateField(blank=True, null=True)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='images/')),
                ('template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualitytemplates')),
            ],
        ),
        migrations.CreateModel(
            name='QualitySamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=100)),
                ('CreateDate', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('requestor', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('pr_no', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('Name', 'template_name', 'Description', 'request_date', 'requestor', 'purpose', 'pr_no')},
            },
        ),
    ]
