# Generated by Django 3.2.16 on 2023-11-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfi_no', models.CharField(max_length=100, unique=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='RFIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.rfi')),
                ('rfi_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglistitem')),
            ],
        ),
        migrations.CreateModel(
            name='VendorsRFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.rfi')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VendorResponseRFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moq', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('lead_time', models.IntegerField(default=0)),
                ('ETA', models.DateField(blank=True, null=True)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.rfi')),
                ('rfi_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.rfiitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
