# Generated by Django 3.2.16 on 2023-11-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
        ('rfi', '0002_alter_vendorsrfi_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSamplesResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_cost', models.IntegerField(default=0)),
                ('sample_ready_date', models.DateField(blank=True, null=True)),
                ('sample_send_date', models.DateField(blank=True, null=True)),
                ('courier_name', models.CharField(max_length=100)),
                ('courier_tracking_no', models.CharField(max_length=100)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.rfi')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.sl_samples')),
            ],
        ),
        migrations.CreateModel(
            name='RFISamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_status', models.CharField(max_length=100)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.sl_samples')),
            ],
        ),
    ]
