# Generated by Django 3.2.16 on 2023-11-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0003_rfisamples_vendorsamplesresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfisamples',
            name='rfi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rfi.rfi'),
            preserve_default=False,
        ),
    ]
