# Generated by Django 3.2.16 on 2023-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0005_alter_rfisamples_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfisamples',
            name='sample_qty',
            field=models.IntegerField(default=0),
        ),
    ]
