# Generated by Django 3.2.16 on 2023-12-01 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('rfi', '0008_alter_rfisamples_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsamplesresponse',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
