# Generated by Django 3.2.16 on 2023-12-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0009_vendorsamplesresponse_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsamplesresponse',
            name='sample_status',
            field=models.CharField(blank=True, choices=[('In Transit', 'In Transit'), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('REDO', 'REDO'), ('MRB', 'MRB')], default='In Transit', max_length=100, null=True),
        ),
    ]
