# Generated by Django 3.2.16 on 2023-12-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0010_vendorsamplesresponse_sample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsamplesresponse',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsamplesresponse',
            name='courier_tracking_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
