# Generated by Django 3.2.16 on 2023-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0011_auto_20231201_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfisamples',
            name='sample_status',
        ),
        migrations.AlterField(
            model_name='rfisamples',
            name='sample_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendorsamplesresponse',
            name='sample_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Transit', 'In Transit'), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('REDO', 'REDO'), ('MRB', 'MRB')], default='In Transit', max_length=100, null=True),
        ),
    ]
